"""The runtime bundle's file templates, as plain Python string constants.

Templates live as ``string.Template`` constants rather than packaged data
files so the package stays wheel-simple (no ``package_data`` plumbing, no
resource loading). Two delimiter regimes keep escaping sane:

- :data:`COMPOSE_TEMPLATE` uses ``%``-placeholders (:class:`ComposeTemplate`)
  because the compose file is full of ``${VAR}`` interpolations that Docker
  Compose itself resolves from ``.env``, plus ``$$``-escaped shell variables
  in the embedded bash script -- a ``$`` delimiter would force ``$$$$``
  quadruple escaping.
- The DAG templates (:data:`MASTER_DAG_TEMPLATE` and the two sub-DAG
  templates) are standard ``$``-delimiter templates; the generated Python
  source contains no ``$``.

Every Airflow fact encoded here (service set, exact env var names, the
health endpoint, JWT auth, external-python constraints) is cited in
references/airflow3-notes.md.
"""

from string import Template

# The DAG-bundle list every rendering shares (references/airflow3-notes.md,
# "DAG bundles"): Compose injects it into the containers' environment, and
# `hflow deploy`'s DEPLOY.md quotes it verbatim for self-managed Airflow.
# One owner for the JSON so the two paths can never drift.
DAG_BUNDLE_CONFIG_LIST_JSON = (
    '[{"name": "dags-folder", '
    '"classpath": "airflow.dag_processing.bundles.local.LocalDagBundle", '
    '"kwargs": {"path": "/opt/airflow/dags"}}]'
)


class ComposeTemplate(Template):
    """``string.Template`` with ``%name`` / ``%{name}`` placeholders.

    Chosen so the compose file's own ``${VAR}`` interpolation syntax and the
    ``$$``-escaped bash variables pass through untouched; the template text
    must therefore contain no literal ``%`` outside placeholders.
    """

    delimiter = "%"


# The official Airflow 3.3.1 reference compose reduced to LocalExecutor:
# postgres + airflow-init + apiserver/scheduler/dag-processor/triggerer,
# no redis, no celery worker, no flower. Substitutions: %{data_volume_line}
# (local mode: the host data root mounted at /opt/airflow/data; bucket mode:
# the bundle-local ./xcom directory instead -- episodes never touch the host
# filesystem), %{xcom_objectstorage_path} (under whichever of those mounts
# exists), %{dag_bundle_config_list} (the shared
# :data:`DAG_BUNDLE_CONFIG_LIST_JSON`), %{hflow_install_target} (the
# source path, plus the [bucket] extra for bucket data roots),
# %{bucket_credentials_env}/%{bucket_credentials_mount} (provider credential
# passthrough for bucket data roots; empty in local mode), and the two
# optional hflow-source mount suffixes (empty when unset).
COMPOSE_TEMPLATE = ComposeTemplate(
    """\
# Generated by hflow render_bundle -- re-rendering overwrites this file
# (only .env survives re-renders). The Airflow 3.3.1 reference compose
# reduced to LocalExecutor: broker and distributed-worker services removed.
# Facts cited in references/airflow3-notes.md.

# A unique project name per bundle: without it Compose defaults to the bundle
# directory's basename ("runtime" for every default bundle), so two projects
# on one machine would silently adopt and destroy each other's stacks and
# share named volumes.
name: %{project_name}

x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE}
  user: "${AIRFLOW_UID}:0"
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__API_AUTH__JWT_SECRET: ${JWT_SECRET}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DAG_PROCESSOR__DAG_BUNDLE_CONFIG_LIST: '%{dag_bundle_config_list}'
    AIRFLOW__CORE__XCOM_BACKEND: airflow.providers.common.io.xcom.backend.XComObjectStorageBackend
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_PATH: %{xcom_objectstorage_path}
    AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_THRESHOLD: '4096'
    # hflow's pinned ffmpeg (a measuring instrument, downloaded once and
    # sha256-verified) caches under XDG_CACHE_HOME; pointing it into the
    # user-venv volume makes the download survive container restarts instead
    # of repeating into an ephemeral container home. Bucket data roots also
    # put their spool mirrors under this cache, so downloads persist too.
    XDG_CACHE_HOME: /opt/venvs/cache%{bucket_credentials_env}
  # User secrets (hflow ui, Secrets tab) become container env here; the values
  # stay in the user's config dir, never in the bundle. Optional so a hand-run
  # compose still works if the file was deleted. Keys set in `environment:`
  # above win over the file, so a secret cannot clobber the runtime's own
  # settings.
  env_file:
    - path: '%{user_secrets_env_file}'
      required: false
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs%{data_volume_line}
    - ./user:/opt/user:ro
    - user-venv:/opt/venvs%{airflow_hflow_source_mount}%{bucket_credentials_mount}
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully
    user-venv-init:
      condition: service_completed_successfully

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-init:
    <<: *airflow-common
    # The official image entrypoint migrates the DB and creates the admin
    # user when the _AIRFLOW_* variables below are set; `version` is the
    # no-op command it runs afterwards (the reference compose's init idiom).
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  user-venv-init:
    # Build the user's venv inside the shared named volume. This runs as root
    # because Docker creates a fresh named volume root-owned (the
    # airflow uid cannot write it); ownership is handed to ${AIRFLOW_UID}:0
    # before exiting so the task processes can use the venv and cache. The
    # content-hash marker is a create-if-absent checkpoint: unchanged
    # requirements + hflow source skip the rebuild entirely.
    image: ${AIRFLOW_IMAGE}
    user: "0:0"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -euo pipefail
        mkdir -p /opt/venvs/cache
        marker_file=/opt/venvs/user/.hflow-content-hash
        # pendulum silences ExternalPythonOperator's noisy per-task bootstrap
        # probe -- at providers-standard 1.17.0 the venv probe is exactly
        # `import pendulum`, and lazy_object_proxy never crosses into the venv
        # (proxies resolve host-side before pickling), so it is NOT installed.
        # The pin matches apache/airflow:3.3.1's constraint so a future
        # pendulum major can never break context unpickling. Joins the hash
        # input so previously built venvs rebuild exactly once.
        bootstrap_packages="pendulum==3.2.0"
        hflow_install_target='%{hflow_install_target}'
        desired_hash="$$({ echo "bootstrap: $$bootstrap_packages"; echo "install: $$hflow_install_target"; cat /opt/user/requirements.txt 2>/dev/null || true; cat /opt/hflow-src/pyproject.toml 2>/dev/null || true; } | sha256sum | cut -d ' ' -f 1)"
        if [ -f "$$marker_file" ] && [ "$$(cat "$$marker_file")" = "$$desired_hash" ]; then
          chown "${AIRFLOW_UID}:0" /opt/venvs /opt/venvs/cache
          echo "user venv matches content hash $$desired_hash -- skipping rebuild"
          exit 0
        fi
        echo "building user venv for content hash $$desired_hash"
        rm -rf /opt/venvs/user
        python -m venv /opt/venvs/user
        /opt/venvs/user/bin/pip install --no-cache-dir --upgrade pip
        /opt/venvs/user/bin/pip install --no-cache-dir $$bootstrap_packages
        if [ -f /opt/user/requirements.txt ]; then
          /opt/venvs/user/bin/pip install --no-cache-dir -r /opt/user/requirements.txt
        fi
        if [ -d /opt/hflow-src ]; then
          /opt/venvs/user/bin/pip install --no-cache-dir "$$hflow_install_target"
        fi
        # Pre-warm the pinned ffmpeg into the volume-backed cache so the
        # download happens here, under the user's eyes at provision time,
        # instead of stalling the first task. Best-effort (|| true): air-gapped
        # provisioning must still succeed -- the task-time fallback remains.
        XDG_CACHE_HOME=/opt/venvs/cache /opt/venvs/user/bin/python -c 'from hflow.ffmpeg import ffmpeg_path; ffmpeg_path()' || true
        echo "$$desired_hash" > "$$marker_file"
        chown -R "${AIRFLOW_UID}:0" /opt/venvs
    volumes:
      - user-venv:/opt/venvs
      - ./user:/opt/user:ro%{venv_init_hflow_source_mount}

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "127.0.0.1:${API_PORT}:8080"
    healthcheck:
      # /api/v2/monitor/health always answers HTTP 200 (the body carries the
      # per-component statuses); this checks the api-server answers at all,
      # exactly like the reference compose's own healthcheck.
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always

volumes:
  postgres-db-volume:
  user-venv:
"""
)


# The master ingest DAG (Dyna Figure 4's top graph), shared by the Compose
# runtime (render_bundle) and `hflow deploy` (render_deploy_bundle).
# Substitutions: $dag_id, the four $*_dag_id sub-DAG ids, and
# $run_profiles_literal -- a dict literal baked from hflow.steps.
# RUN_PROFILES at render time (steps.py stays the one owner of the profile
# vocabulary; the baked copy is generated code). The master runs ENTIRELY in
# Airflow's own environment: no external_python, no hflow import --
# TriggerDagRunOperator ships in apache-airflow-providers-standard, which the
# official image includes, and its deferrable wait needs the triggerer
# service, which every rendered runtime runs.
MASTER_DAG_TEMPLATE = Template(
    '''\
"""Master ingest DAG "$dag_id" -- generated by hflow; re-render instead of editing.

Dyna Figure 4's master graph: resolve the run profile to its enabled stage
set, then trigger only those sub-DAGs, chained sequentially
(sync >> meta >> labels >> media). Runs entirely in Airflow's own environment
-- no user venv, no hflow import.

Trigger conf: {"uris": [...], "profile": "full", "mode": "batch"|"online",
"batch_count": optional int}. "uris"/"mode"/"batch_count" pass through to
every triggered sub-DAG; mode "online" is the latency-first lane (one run per
episode as it lands): each sub-DAG processes the conf's uris as one immediate
batch, no bin-packing, no stagger.

How Figure 4's stage toggles map onto tasks: the profile arrives in the run
conf, so which stages run cannot be a parse-time conditional. Instead every
stage's trigger always exists behind its own enabled_<stage> gate task, and a
gate raises AirflowSkipException when the resolved profile disables its stage
-- the skip cascades to exactly that stage's trigger (default all_success
rule), while the next gate's trigger_rule="none_failed" lets it run after
skipped (but never failed) predecessors. So the enabled sub-DAGs execute
strictly in sequence, a disabled stage shows as two skipped tasks in the UI,
and a failed sub-DAG still stops the chain. Deliberately NOT a @task.branch:
skip_all_except treats everything downstream of a followed branch as also
followed, and with the triggers chained sequentially that would silently
re-enable every stage after the first enabled one (a "labels"-only profile
would run media too).
"""

from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.sdk import dag, task

# Baked from hflow.steps.RUN_PROFILES at render time -- re-render after
# changing profiles; never edit this literal by hand.
RUN_PROFILE_STAGES = $run_profiles_literal

# Declaration order is Figure 4's left-to-right execution order.
STAGE_SUB_DAG_IDS = {
    "sync": "$sync_dag_id",
    "meta": "$meta_dag_id",
    "labels": "$labels_dag_id",
    "media": "$media_dag_id",
}

# Rendered on the DAG's page in the Airflow UI (the profile table is baked
# from hflow.steps.RUN_PROFILES at render time, like the literal above).
DOC_MD = """\
## Master ingest -- resolves the run profile, triggers only the sub-DAGs it needs

Dyna Figure 4's master graph. Enabled stages run strictly in order
(sync >> meta >> labels >> media); a stage disabled by the profile shows as
two **skipped** tasks, and a teal **deferred** trigger task is intentionally
waiting on its sub-DAG run to finish.

| run profile | stages enabled |
|---|---|
$profile_table_rows

**Trigger conf** -- `uris`: episode files relative to the data root;
`profile`: a row above (default `full`); `mode`: `batch` bin-packs uris into
staggered near-equal-byte shards, `online` is the latency-first lane (one
immediate run, no batching, no stagger); `batch_count`: optional override.

Each sub-DAG (`$sync_dag_id`, `$meta_dag_id`, `$labels_dag_id`,
`$media_dag_id`) is also directly triggerable with the same conf for
per-stage reruns -- e.g. a re-label pass over already-canonical episodes.
"""


@dag(
    dag_id="$dag_id",
    dag_display_name="$master_display_name",
    description="Resolves the run profile and triggers only the enabled stage sub-DAGs.",
    doc_md=DOC_MD,
    tags=["$pipeline_tag", "master"],
    schedule=None,
    render_template_as_native_obj=True,
    params={"uris": [], "profile": "full", "mode": "batch", "batch_count": None},
)
def master_ingest():
    @task
    def resolve_profile(profile, mode):
        """Validate the conf against the baked vocabulary; return the enabled stages."""
        if profile not in RUN_PROFILE_STAGES:
            raise ValueError(
                f"unknown run profile {profile!r}; valid profiles: "
                f"{sorted(RUN_PROFILE_STAGES)}"
            )
        if mode not in ("batch", "online"):
            raise ValueError(f"unknown mode {mode!r}; valid modes: batch, online")
        return list(RUN_PROFILE_STAGES[profile])

    @task(trigger_rule="none_failed")
    def stage_gate(stage_name, enabled_stage_names):
        """Skip this stage's trigger when the profile disables it (Figure 4 toggle)."""
        from airflow.exceptions import AirflowSkipException

        if stage_name not in enabled_stage_names:
            raise AirflowSkipException(
                f"stage {stage_name!r} disabled by the run profile "
                f"(enabled: {enabled_stage_names})"
            )

    enabled_stage_names = resolve_profile(
        profile="{{ params.profile }}", mode="{{ params.mode }}"
    )

    previous_trigger = None
    for stage_name, sub_dag_id in STAGE_SUB_DAG_IDS.items():
        gate = stage_gate.override(task_id=f"enabled_{stage_name}")(
            stage_name, enabled_stage_names
        )
        trigger = TriggerDagRunOperator(
            task_id=f"trigger_{stage_name}",
            # A teal "deferred" state reads as stalled to demo audiences;
            # the display name and doc say the wait is intentional.
            task_display_name=f"trigger {stage_name} · waits (deferred)",
            doc_md=(
                f"Triggers `{sub_dag_id}` and waits (deferred, checked every "
                "5s) for that run to finish before the next stage's gate."
            ),
            trigger_dag_id=sub_dag_id,
            conf={
                "uris": "{{ params.uris }}",
                "mode": "{{ params.mode }}",
                "batch_count": "{{ params.batch_count }}",
            },
            wait_for_completion=True,
            deferrable=True,
            # Measured (2026-08-18): the deferral wait wastes ~poke_interval/2
            # per hop after a sub-DAG finishes; at local run volumes a 2s poll
            # costs the triggerer nothing and saves ~1.5s per stage hop.
            poke_interval=2,
        )
        gate >> trigger
        if previous_trigger is not None:
            previous_trigger >> gate
        previous_trigger = trigger


master_ingest()
'''
)


# The sub-DAG templates (Figure 4's four toggleable sub-DAGs), shared by the
# Compose runtime and `hflow deploy`. Substitutions: $dag_id,
# $master_dag_id, $stage_title, $stage_name, $gate_name, $pipeline_filename,
# $app_variable, plus the two facts the deployments disagree on -- $data_root
# (where episode URIs resolve inside the task processes) and $venv_python
# (the user venv's interpreter). Every task runs via @task.external_python
# against the user venv, so ALL imports live inside the function bodies (the
# operator extracts each body to a temp file; module globals do not survive)
# and everything passed between tasks is plain JSON-able data. The two
# variants differ only in the gate: checks decide quarantine, so the
# quarantine budget lives ONLY in the meta sub-DAG; every other stage keeps
# the error-budget half.
_SUB_DAG_HEADER = '''\
"""$stage_title sub-DAG "$dag_id" -- generated by hflow; re-render instead of editing.

One of Figure 4's four toggleable sub-DAGs, normally triggered by the master
DAG "$master_dag_id" (direct triggering with the same conf also works).
plan -> process_batch (dynamically mapped) -> $gate_name, all via
@task.external_python against the user venv at $venv_python (user dependencies
never meet Airflow's pins). Imports live inside the function bodies because
the operator extracts each body to a temp file; only JSON-able data crosses
task borders. Trigger conf: {"uris": [...], "mode": "batch"|"online",
"batch_count": optional int}.
"""

from airflow.sdk import dag, task

# Rendered on the DAG's page in the Airflow UI.
DOC_MD = """\
## $stage_title -- stage sub-DAG

$stage_description

Normally triggered by the master DAG `$master_dag_id` (Figure 4's profile
toggles decide which stages run); triggering it directly with the same conf
also works, for per-stage reruns. Tasks execute in the isolated user venv --
user dependencies never meet Airflow's pins.

**Trigger conf** -- `uris`: episode files relative to the data root;
`mode`: `batch` (bin-packed, staggered shards) or `online` (one immediate
latency-first run); `batch_count`: optional override.
"""


@dag(
    dag_id="$dag_id",
    dag_display_name="$sub_display_name",
    description="$stage_description",
    doc_md=DOC_MD,
    tags=["$pipeline_tag", "stage:$stage_name"],
    schedule=None,
    render_template_as_native_obj=True,
    params={"uris": [], "mode": "batch", "batch_count": None},
)
def ingest_stage():
    @task.external_python(python="$venv_python", expect_airflow=False, skip_on_exit_code=99)
    def plan(uris, mode, batch_count):
        """Bin-pack uris into staggered batches; online is one immediate batch."""
        from hflow.batching import plan_batches
        from hflow.storage import parse_storage_root

        if not uris:
            return []
$stage_plan_filter        if mode == "online":
            # The online lane (Figure 4) is latency-first: one run per episode
            # as it lands -- no batching, no stagger, batch_count ignored.
            return [{"items": [str(uri) for uri in uris], "start_delay_s": 0.0}]
        data_root = parse_storage_root("$data_root")
        item_sizes = {str(uri): data_root.file_size(str(uri)) for uri in uris}
        resolved_batch_count = (
            int(batch_count) if batch_count is not None else min(4, len(item_sizes))
        )
        planned = plan_batches(
            item_sizes, batch_count=resolved_batch_count, stagger_interval_s=2.0
        )
        return [
            {"items": list(batch.items), "start_delay_s": batch.start_delay_s}
            for batch in planned
        ]

    @task.external_python(python="$venv_python", expect_airflow=False)
    def process_batch(batch):
        """Sleep the stagger delay, then run this sub-DAG's stage on every episode."""
        import importlib.util
        import os
        import time
        import traceback
        from pathlib import Path

        from hflow.storage import is_bucket_url

        time.sleep(float(batch["start_delay_s"]))

        pipeline_path = "/opt/user/" + "$pipeline_filename"
        # Managed platforms cannot always mount user/ at /opt/user;
        # HFLOW_USER_DIR relocates it without re-rendering (DEPLOY.md names
        # the per-platform value).
        user_dir_override = os.environ.get("HFLOW_USER_DIR")
        if user_dir_override:
            pipeline_path = user_dir_override.rstrip("/") + "/" + "$pipeline_filename"
        spec = importlib.util.spec_from_file_location("hflow_user_pipeline", pipeline_path)
        if spec is None or spec.loader is None:
            raise RuntimeError("cannot load user pipeline at " + pipeline_path)
        pipeline_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(pipeline_module)
        app = getattr(pipeline_module, "$app_variable")
        # Episode URIs resolve under the runtime's data root; an app pointing
        # anywhere else would silently write elsewhere in the
        # task's filesystem, so refuse loudly instead.
        if str(app.data_root) != "$data_root":
            raise RuntimeError(
                "pipeline data_root must be $data_root inside the runtime; "
                f"it is {app.data_root}"
            )

        data_root = str(app.data_root)
        counts = {"processed": 0, "quarantined": 0, "errors": 0}
        for uri in batch["items"]:
            try:
                episode_reference = (
                    data_root.rstrip("/") + "/" + str(uri).lstrip("/")
                    if is_bucket_url(data_root)
                    else Path(data_root) / str(uri)
                )
                report = app.process(
                    episode_reference, record=True, stages={"$stage_name"}
                )
            except Exception:
                # Per-episode crashes are counted as errors, never batch-fatal;
                # the gate applies the run budget to the error tally (and an
                # all-errors run always fails), so mass failure stays loud.
                traceback.print_exc()
                counts["errors"] += 1
                continue
            if report.has_errors:
                # app.process collects per-step diagnostics for the dev loop
                # and catalog, so step failures are explicit report outcomes
                # rather than escaping exceptions. They still count against
                # the runtime's infrastructure-error budget.
                counts["errors"] += 1
            elif report.quarantined:
                counts["quarantined"] += 1
            else:
                counts["processed"] += 1
        return counts
'''

_SUB_DAG_QUARANTINE_GATE = '''\

    @task.external_python(python="$venv_python", expect_airflow=False)
    def quarantine_budget_gate(batch_counts):
        """Fail the run loudly on mass failure of either kind.

        Checks decide quarantine, so the quarantine budget lives ONLY in this
        meta sub-DAG. The same budget also applies to per-episode exceptions
        and step errors collected in TestReport, and a run where nothing
        processed at all always fails.
        """
        import math

        total = sum(
            counts["processed"] + counts["quarantined"] + counts["errors"]
            for counts in batch_counts
        )
        quarantined = sum(counts["quarantined"] for counts in batch_counts)
        errors = sum(counts["errors"] for counts in batch_counts)
        budget = max(8, math.ceil(0.01 * total))
        if quarantined > budget:
            raise RuntimeError(
                f"quarantined {quarantined} of {total} episodes, over the budget "
                f"of {budget} -- quarantine is a tag, never a deletion; inspect "
                "the catalog's quarantine tags"
            )
        if errors > budget or (errors and errors == total):
            raise RuntimeError(
                f"{errors} of {total} episodes had processing errors "
                f"(budget {budget}) -- infrastructure, not data; see the "
                "process_batch task logs"
            )
        return {
            "total": total,
            "quarantined": quarantined,
            "errors": errors,
            "budget": budget,
        }
'''

_SUB_DAG_ERROR_GATE = '''\

    @task.external_python(python="$venv_python", expect_airflow=False)
    def error_budget_gate(batch_counts):
        """Fail loudly when processing errors exceed the run budget.

        Quarantine budgets live only in the meta sub-DAG (checks decide
        quarantine); here quarantined episodes just count toward the total,
        and a run where every episode errors always fails.
        """
        import math

        total = sum(
            counts["processed"] + counts["quarantined"] + counts["errors"]
            for counts in batch_counts
        )
        errors = sum(counts["errors"] for counts in batch_counts)
        budget = max(8, math.ceil(0.01 * total))
        if errors > budget or (errors and errors == total):
            raise RuntimeError(
                f"{errors} of {total} episodes had processing errors "
                f"(budget {budget}) -- infrastructure, not data; see the "
                "process_batch task logs"
            )
        return {"total": total, "errors": errors, "budget": budget}
'''

_SUB_DAG_FOOTER = """\

    batches = plan(
        uris="{{ params.uris }}",
        mode="{{ params.mode }}",
        batch_count="{{ params.batch_count }}",
    )
    batch_counts = process_batch.expand(batch=batches)
    # The mapped task's aggregated XCom is a lazy proxy that cannot cross the
    # external-python pickle boundary (it references the in-DAG callable), so
    # the gate pulls it via a template: `| list` materializes plain dicts
    # during native-object rendering. task_ids MUST be a list -- a plain
    # string makes xcom_pull flatten a single-batch run to the bare counts
    # dict. The >> keeps the dependency explicit.
    gate = $gate_name(
        batch_counts="{{ ti.xcom_pull(task_ids=['process_batch']) | list }}"
    )
    batch_counts >> gate


ingest_stage()
"""

SUB_DAG_QUARANTINE_GATE_TEMPLATE = Template(
    _SUB_DAG_HEADER + _SUB_DAG_QUARANTINE_GATE + _SUB_DAG_FOOTER
)
SUB_DAG_ERROR_GATE_TEMPLATE = Template(_SUB_DAG_HEADER + _SUB_DAG_ERROR_GATE + _SUB_DAG_FOOTER)


# Injected into the media sub-DAG's plan (empty for other stages, and for
# BUCKET data roots -- reading a remote episode's channel list would download
# the whole file, which costs more than the skipped cycle saves): media
# derives per-camera artifacts, so camera-less episodes would pay a full
# plan -> map -> gate cycle (~10s measured 2026-08-18) to record nothing.
# When nothing in the run has cameras the plan exits 99, which
# skip_on_exit_code turns into a SKIPPED task (the UI shows the stage never
# applied, not a hollow success); downstream tasks skip with it.
MEDIA_PLAN_FILTER_TEMPLATE = Template(
    """\
        from pathlib import Path

        from hflow.format import CAMERA_SCHEMA_NAMES
        from hflow.reader import open_reader

        def has_camera(uri):
            reader = open_reader(Path("$data_root") / str(uri))
            try:
                return any(
                    info.schema_name in CAMERA_SCHEMA_NAMES
                    for info in reader.channels().values()
                )
            finally:
                reader.close()

        # Media applies only to camera-bearing episodes (see template note).
        uris = [uri for uri in uris if has_camera(uri)]
        if not uris:
            raise SystemExit(99)  # skip_on_exit_code: whole stage SKIPPED
"""
)
